version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    container_name: gradescopesync
    restart: unless-stopped
    volumes: #mounting for real time changes
      - .:/app
